### ISSUE TITLE
Aesthetics and details

### ISSUE THREAD

**Issue by eroten** [Metropolitan-Council/regionalparks.acs#19]
- [x] ditch `absolutePanel()`s; they cause accessibility issues
- [x] set max width for entire app; current width is WAY too wide
- [x] use consistent basemap for all leaflet plots
- [x] ~~use consistent margin and border values for all objects~~
- [x] detailed review of `inst/app/style.css`
- [x] check text hierarchy sizes
- [x] ~~do cursory mobile-ready evaluation~~
- [x] plotly styling
  - [x] axis typeface and title
  - [x] hover box text, typeface, text color, background color, opacity
- [x] review user instructions and narrative text (will involve Darcie and Krysten)
- [x] consider using a loading spinner on maps and plots
- [x] update package references
- [x] review Intro and note tabs css

**Comment by eroten** [comment]
@ehesch do you want me to take a stab at loading spinners? I've had success in the past using [`{waiter}`](https://github.com/JohnCoene/waiter). There is a spiffy demo page [here](https://waiter.john-coene.com/#/)

**Comment by ehesch** [comment]
@eroten , sorry! didn't see this until now. I can probably add a spinner - I've made some changes as you probably noticed. Most saliently I moved away from plotly in favor of ggplot (in order to have the plots include the "agency average" and also look decent regardless of how many points are selected - apparently a concern is that folks might grab the figures directly from the app, and thus I thought it prudent to have the best figs possible, even if the interactivity is a bit less elegant. I'll do a push tomorrow morn and we can chat about what's up?

**Comment by eroten** [comment]
@ehesch no worries! I made a few aesthetic changes (font and icon sizes, park status colors, padding), adjusted the HTML paragraph text, restricted the zoom level on the transit stops layer in leaflet, and tried to fix the issue with #22 (no luck). Everything is pushed to the `19-aesthetics-and-details` branch. 😃

**Comment by ehesch** [comment]
@eroten what do you think about having a single color palette for all acs variables? These palettes aren't working so well with the park/trail colors (to be fair, having multiple palettea playing nicely with the 3 park/trail colors is a big ask!). 

![Screen Shot 2020-12-29 at 11 32 47 AM](https://user-images.githubusercontent.com/69309226/103302679-cd817680-49c9-11eb-9258-3d037b80a3a4.png)
![Screen Shot 2020-12-29 at 11 33 01 AM](https://user-images.githubusercontent.com/69309226/103302683-cf4b3a00-49c9-11eb-8b91-65850e0a57f8.png)
![Screen Shot 2020-12-29 at 11 33 07 AM](https://user-images.githubusercontent.com/69309226/103302686-cfe3d080-49c9-11eb-9fcc-3f5aaf3096c9.png)
![Screen Shot 2020-12-29 at 11 33 13 AM](https://user-images.githubusercontent.com/69309226/103302687-d07c6700-49c9-11eb-8477-90c933ec255c.png)
![Screen Shot 2020-12-29 at 11 33 31 AM](https://user-images.githubusercontent.com/69309226/103302688-d114fd80-49c9-11eb-93e9-25c98701f676.png)

**Comment by eroten** [comment]
I think that would be fine! The legend and popup will update, so that will help reduce confusion. The changing color palettes worked well when we wanted to clearly differentiate each set (Race, Ethnicity, Age), but since we are balancing more colors, it should be fine to just choose the best palette that works with the park status colors

**Comment by ehesch** [comment]
PS, I'm changing the color palette again...if there's a bigger reason to have the colors be of a certain palette that's fine and I'm happy with whatever! But my [fave colorblindness simulator ](https://davidmathlogic.com/colorblind) wasn't a big fan of the green/teal/brown scheme. 

![Screen Shot 2020-12-29 at 5 04 41 PM](https://user-images.githubusercontent.com/69309226/103320325-7c3dab00-49fa-11eb-8133-eb0757a5d4c7.png)

I've modified the hues a bit (darker green, lighter teal, brighter organge/yellow) and it's seeming more accessible (and a couple colors from a blue palette are thrown in there just for fun too (testing an option for the leaflet color palette). 

![Screen Shot 2020-12-29 at 5 18 31 PM](https://user-images.githubusercontent.com/69309226/103320360-a5f6d200-49fa-11eb-81eb-8722eef3ad0b.png)

**Comment by ehesch** [comment]
hmmm, well that wasn't working super well for my eyes.... have migrated to this option for now...
![Screen Shot 2020-12-29 at 5 44 58 PM](https://user-images.githubusercontent.com/69309226/103359014-a5068480-4a7c-11eb-9eb7-579f4c327b4f.png)

**Comment by eroten** [comment]
I like the color choices! I'm also going to bookmark that web page. 

I do want to note that `#78A22F` is the Council's CD brand green. If we want to use a green there, its probably a safer bet than another green we generate. You can see a few other colors in [`inst/app/www/colors.css`](https://github.com/Metropolitan-Council/regionalparks.acs/blob/master/inst/app/www/colors.css). There is also list in `{councilR}` you can access with `councilR::colors`


Since we are also using these colors as backgrounds for the text above the summary plot, I've been checking the [contrast ratio](https://webaim.org/resources/contrastchecker/) with black text. These colors are looking good!

**Comment by ehesch** [comment]
@eroten waiter added to maps, not sure I love its current iteration but definitely like the idea!

**Comment by ehesch** [comment]
@eroten YAY - deployed, working, etc.! Much speedier too. Not 100% sure what was causing some of the funky issues. Rebuilding did give an opportunity to clean up each module, the entire package, etc. which is a nice consolation prize I guess?! 🤷

[CHECK IT OUT!](https://metrotransitmn.shinyapps.io/buffer2)

Re-creating/updating your checklist....
- [ ] re-consider adding a waiter
- [ ] *&!$ leaflet doesn't render polygons until the maps are interacted with! The fix from before does not get along with the deployment ....
- [ ] consider styling on sidepanels for Map pane, especially (it's quite long currently)
- [ ] consider adding button for [leaflet.extras::fullscreen](https://rdrr.io/github/bhaskarvk/leaflet.extras/man/fullscreen.html) (was slowing things down when I was doing this, so it didn't seem worth it?)
- [ ] consider adding mapshot and/or [broadband style downloadable map](https://github.com/katiejolly/broadband-maps/blob/master/app/app.R) to a tab where individual units can be isolated with the map polygons
- [ ] consider putting legend back in ggplot summary maps so it downloads with plot
- [ ] i kind of hate the leaflet percentile legends....would be nice to show the real numbers
- [ ] might be nice if leaflet legends could be drug around by users

Longer term...
- [ ] text input from colleagues
- [ ] user experience input from colleagues
- [ ] detailed user guide
- [ ] can we automate updates (ie pop forecasts are re-done quarterly, acs updated annually) OR include some kind of obvious way users can note the "vintage" of the data pieces

**Comment by ehesch** [comment]
urg, download button on the summary --> table isn't working :/ not sure what's going on there.....

**Comment by eroten** [comment]
@ehesch Hooray! The app is so much faster now, and has cleaned up nicely!

I took some of the checklist items in your last comment and broke them into two new issues (#23 and #24). Its generally better to have several smaller issues rather than one massive one, particularly since we are venturing outside appearance changes with this issue. I've crossed out the items that I moved to other issues. 

> * [ ]  re-consider adding a waiter
> * [ ] ~~*&!$ leaflet doesn't render polygons until the maps are interacted with! The fix from before does not get along with the deployment ....~~
> * [ ]  consider styling on sidepanels for Map pane, especially (it's quite long currently)
> * [ ]  ~~consider adding button for [leaflet.extras::fullscreen](https://rdrr.io/github/bhaskarvk/leaflet.extras/man/fullscreen.html) (was slowing things down when I was doing this, so it didn't seem worth it?)~~
> * [ ] ~~consider adding mapshot and/or [broadband style downloadable map](https://github.com/katiejolly/broadband-maps/blob/master/app/app.R) to a tab where individual units can be isolated with the map polygons~~
> * [ ]  consider putting legend back in ggplot summary maps so it downloads with plot
> * [ ]  ~~i kind of hate the leaflet percentile legends....would be nice to show the real numbers~~
> * [ ]  ~~might be nice if leaflet legends could be drug around by users~~
> 
> Longer term...
> 
> * [ ]  ~~text input from colleagues~~
> * [ ]  ~~user experience input from colleagues~~
> * [ ]  ~~detailed user guide~~
> * [ ]  ~~can we automate updates (ie pop forecasts are re-done quarterly, acs updated annually) OR include some kind of obvious way users can note the "vintage" of the data pieces~~

The only three items left are 

- [ ] re-consider adding a waiter
- [ ] consider styling on sidepanels for Map pane, especially (it's quite long currently)
- [ ] consider putting legend back in ggplot summary maps so it downloads with plot

**Comment by ehesch** [comment]
have reconsidered the `waiter`; I think it's no longer necessary becuase the app has been lightened significantly (only 1 map!) and no longer takes forever and a year to load :)
