### ISSUE TITLE
app not uploading to shiny server

### ISSUE THREAD

**Issue by ehesch** [Metropolitan-Council/regionalparks.acs#21]
@eroten I'm trying to push branch 19 (aesthetics, etc) to the shiny server (either "bufferapp" or "bufferstyletest", or other). I think that would be good to have for Friday's meeting. 

HOWEVER, I am getting plagued by errors! (and yes, I know that some of the file paths are not ideal right now in the data-raw, but I'd like to keep that in there until the MN Geospatial Commons has some updated data). 

Mainly, I'm confused at why `%>%` can't be found even though there is a `utils-pipe.R` script? Thanks for any tips!

![Screen Shot 2020-12-15 at 1 55 42 PM](https://user-images.githubusercontent.com/69309226/102266102-9bf2b080-3edd-11eb-86a5-83accb56527b.png)

**Comment by eroten** [comment]
Try restarting and building the package (Cmd + Shift + B) and give it another go.
