### ISSUE TITLE
print(namespace)?

### ISSUE THREAD

**Issue by ehesch** [Metropolitan-Council/regionalparks.acs#22]
Hi @eroten - the leaflet issue not rendering [is by design](https://github.com/rstudio/leaflet/issues/590) (although annoyingly so, imo)! 

So it seems like a quick fix to have one of the observers notice which tab the app is on (and in this case, fire the observeevent if the app is on the map tab, or the buffer map tabset). However...the namespaces are bogging me down again 😭. What's the logical way to print the name of the tab which the app is on? 

Thanks!

**Comment by eroten** [comment]
See if you can figure out the HTML id on the map tab. It will be something long, like `id=app_ui-Map`. The ID  will have both the module *and* element IDs, so you can track it down that way.

**Comment by eroten** [comment]
@ehesch I will take a look at this today. A potential workaround is to have a pop-up or message that tells the user to make a selection
