### ISSUE TITLE
Map bug fixes and enhancements

### ISSUE THREAD

**Issue by eroten** [Metropolitan-Council/regionalparks.acs#24]
# Bugs

- [x] ❗ HIGH PRIORITY ❗  leaflet doesn't render polygons until the maps are interacted with! The fix from before does not get along with the deployment ....
- [x] app title needs margins on mobile 
- [x] update main navbar/tabs to style guide
- [x] ❗ HIGH PRIORITY ❗  app is having deployment issues again, quitting before maps are rendered, etc. [https://metrotransitmn.shinyapps.io/buffer3](https://metrotransitmn.shinyapps.io/buffer3)

# Enhancement
- [ ] i kind of hate the leaflet percentile legends....would be nice to show the real numbers
- [ ] might be nice if leaflet legends could be drug around by users
- [ ] consider adding button for [leaflet.extras::fullscreen](https://rdrr.io/github/bhaskarvk/leaflet.extras/man/fullscreen.html) (was slowing things down when I was doing this, so it didn't seem worth it?)
- [ ] consider adding mapshot and/or [broadband style downloadable map](https://github.com/katiejolly/broadband-maps/blob/master/app/app.R) to a tab where individual units can be isolated with the map polygons
- [ ] might be nice if leaflet legends could be drug around by users

![Screen Shot 2021-01-06 at 9 48 46 AM](https://user-images.githubusercontent.com/69309226/103788415-6df81c00-5004-11eb-976d-4d14ba651a47.png)

See #19

**Comment by ehesch** [comment]
@eroten I pushed the [v1.0.0 to the shiny server](https://metrotransitmn.shinyapps.io/buffer3) (so exciting to have a lot of those big changes implemented!). And as such needed to add a new bug to the running list here (deployment issues, app is disconnecting before all map rendering can be completed, etc.)

**Comment by ehesch** [comment]
- [ ]  % rent burdened by AMI; add to app from this source: https://metrocouncil.org/Housing/Planning/Affordable-Housing-Measures.aspx
