### ISSUE TITLE
preference for map with conditional panel or not?

### ISSUE THREAD

**Issue by ehesch** [Metropolitan-Council/regionalparks.acs#37]
Hi @eroten, I'd appreciate if you could do a quick `run_dev` on [the latest push](https://github.com/ehesch/regionalparks.acs/tree/31-polishing). 

On the System Map tab, I've removed the conditional panel and would love to know your thoughts on that. I see pros and cons to each. But....I'd *probably* put a vote in for *no* conditional panels. Would really like your second opinion here, thanks! :)

**Comment by eroten** [comment]
So, from what I'm seeing, you removed the "Variable to map" select input (which updated based on "Choose your data source") and just added another sub-section to "Variable to map".

I think that having "Choose your data source" is useful for clearly designating that the user is mapping two different data sources. Another way to do this (without the data source conditional panel) would to add another subsection heading, so it would be something like this.

> ## Choose your variable
>### ACS variables
> -  foreign born
> -  (all other ACS vars)
> ### Population forecast variables
>  - Absolute change by 2040
> -  (all other population vars) 


This may eliminate the extra performance lag with the conditional panel

**Comment by ehesch** [comment]
@eroten nice idea, thanks for the thoughts!
