### ISSUE TITLE
water layer is the slow piece!

### ISSUE THREAD

**Issue by ehesch** [Metropolitan-Council/regionalparks.acs#49]
@eroten  the layer with rivers and lakes is making this app SLOW! Not the census data. I discovered this when I thought adding water would be nice in a different app (I have now reconsidered that). Do you know is there a way that we can "smooth" the geometry of the rivers/lakes so that the file is smaller and quicker to load? It does seem to be an issue that should be tackled when creating the rda file, rather than introducing a smoother in the leaflet (that doesn't make a noticeable difference in load speed). 

I explored a couple things using the sf package, but nothing was a ringer for me. I am hoping you have other ideas?

**Comment by eroten** [comment]
Yeah, water polygons can be pretty complex. I have a couple ideas here. 

- Try breaking out the water features by class, such that there is a separate layer for rivers and another for lakes. 
- Check out [`sf::st_simplify()`](https://r-spatial.github.io/sf/reference/geos_unary.html). You can run this when you create the dataset for the package.
- Another option is to use [`{smoothr}`](https://github.com/mstrimas/smoothr/). I haven't used this package before, but it might be useful!

We may want to make a note somewhere that the water boundaries are not definitive, just for general reference.

**Comment by ehesch** [comment]
#50 includes st_simplify
