### ISSUE TITLE
make sure labels are right

### ISSUE THREAD

**Issue by ehesch** [Metropolitan-Council/regionalparks.acs#5]
I had a question about the Pt. Douglas Regional Trail. Some of it is in St. Paul’s jurisdiction, but the label says “Bruce Vento-Washington County.” Should that label say “St. Paul Parks and Recreation-Washington County”?

**Comment by eroten** [comment]
There should be two separate geographies for Pt. Douglas: one for St. Paul and one for Washington County. I think the planned, St. Paul Point Douglas trail is supposed to connect Bruce Vento RT(?), which might explain the wonky label.

In the existing units, the IA is in italics in the label. There may not be an IA listed in the RT search area units (or its listed under a different column name).
